server:
  port: 10002
spring:
  application:
    name: gateway
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        service-name: gateway

    gateway:
      discovery:
        locator:
          lower-case-service-id: true

        #      - id: USER-SERVICE            #网关路由到用户服务user-service
        #        uri: lb://USER-SERVICE
        #        predicates:
        #          - Pach=/USER-SERVICE/**
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**

      - id: userTaskInfo
        uri: lb://user
        predicates:
        - Path=/cms/getUser
        filters:
        - RewritePath=/cms/getUser, /user/getUser

    bus:
      trace:
        enabled: true
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: info